services:
  - type: web
    name: miniopenfx
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build && pnpm db:migrate
    startCommand: pnpm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: API_KEY
        generateValue: true
      - key: NODE_VERSION
        value: 20.10.0
